s =set()
n= int(input("Enter the number of elements: "))
s.add(n)
n= int(input("Enter the number of elements: "))
s.add(n)
n= int(input("Enter the number of elements: "))
s.add(n)
n= int(input("Enter the number of elements: "))
s.add(n)
n= int(input("Enter the number of elements: "))
s.add(n)
print(s)